org: felipeneuhauss
app: graphql-dynamodb
service: graphql-dynamodb

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  stage: ${opt:stage, "dev"}
  lambdaHashingVersion: 20201221
  variablesResolutionMode: 20210326
  environment:
    HEROES_TABLE: Heroes
    SKILLS_TABLE: Skills
    LOCALSTACK_HOSTNAME: ${env:LOCALSTACK_HOSTNAME, "localhost"}
    DYNAMODB_PORT: ${env:DYNAMODB_PORT, "4566"}
  iamRoleStatements: # cloud formation
    - Effect: Allow
      Action:
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:Scan
        - dynamodb:Query
        - dynamodb:DescribeTable
      Resource:
        - "arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.HEROES_TABLE}"
        - "arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.SKILLS_TABLE}"

package:
  excludeDevDependencies: true # remove as dependencias da publicacao
  individually: true

plugins:
  - serverless-dynamodb-local
  - serverless-offline

custom:
  dynamodb:
    stages:
      - ${self:provider.stage}
    start:
      host: ${self:provider.environment.LOCALSTACK_HOSTNAME}
      port: ${self:provider.environment.DYNAMODB_PORT}
      migrate: true
      noStart: true
      seed: true
    seed:
      heroes:
        sources:
          - table: ${self:provider.environment.HEROES_TABLE}
            source: ['./seeds⁄heroes.json']
      skills:
        sources:
          - table: ${self:provider.environment.SKILLS_TABLE}
            source: ['./seeds⁄skills.json']

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: any

resources:
  Resources:
    Heroes:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.HEROES_TABLE}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    Skills:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.SKILLS_TABLE}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

