org: felipeneuhauss
app: image-resize
service: aws-node-project

frameworkVersion: '2'


provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  region: us-east-1
  memorySize: 256
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:GetObject
        - s3:PutObject
      Resource:
        - "arn:aws:s3:::*"
  environment:
    IMAGES_UPLOADED_BUCKET: felipeneuhauss-storage

functions:
  optimize:
    handler: optimize.handle
    events:
      - s3:
          bucket: ${self:provider.environment.IMAGES_UPLOADED_BUCKET}
          event: s3:ObjectCreated:*
          existing: true
          rules:
            - prefix: uploads/
            - suffix: .png
      - s3:
          bucket: ${self:provider.environment.IMAGES_UPLOADED_BUCKET}
          event: s3:ObjectCreated:*
          existing: true
          rules:
            - prefix: uploads/
            - suffix: .jpg
