version: "3.8"

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack-full
    network_mode: bridge
    ports:
      - "127.0.0.1:53:53"
      - "127.0.0.1:53:53/udp"
      - "127.0.0.1:443:443"
      - "127.0.0.1:4566:4566"
      - "127.0.0.1:4571:4571"
      - "127.0.0.1:${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - START_WEB=1
      - SERVICES=s3,sqs
      - LAMBDA_EXECUTOR=local
      - LAMBDA_REMOTE_DOCKER=$TMPDIR
      - DOCKER_HOST=unix:///var/run/docker.sock
      - PORT_WEB_UI=4581
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

  app:
      build: .
      volumes:
          - .:/src
          - nodemodules:/src/node_modules
      restart: on-failure
      # command: npm test
      ports:
          - 3000:3000
      links:
          - localstack
      depends_on:
          - localstack
      environment:
          LOCALSTACK_HOST: localstack
          S3_PORT: 4566

volumes:
    nodemodules: {}


